build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py

publish:
    docker:
        repo: mazcodes/cicd_demoapp
        tag: latest
        username: mazcodes
        password: ICodeThereforeIam
        email: mabounaj@cisco.com

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: SEVT1
            password: SEVT1
        urls:
            - https://control.sandbox.imapex.io/marathon/v2/apps/class/mazcodes/restart?force=true

# Replace USERNAME with your GitHub username
# drone secure --repo USERNAME/cicd_demoapp --in drone_secrets.yml
#
# # add the file to the git repo
# git add .drone.sec
# git add .drone.yml
#
# # commit the change
# git commit -m "Added Deploy phase to restart application"
#
# # push changes to GitHub
# git push
#
# build: build_starting: image: python:2 commands: - echo "Beginning new build" run_tests: image: python:2-alpine commands: - pip install -r requirements.txt - python testing.py publish: docker: repo: $$DOCKER_USERNAME/cicd_demoapp tag: latest username: $$DOCKER_USERNAME password: $$DOCKER_PASSWORD email: $$DOCKER_EMAIL deploy: webhook: image: plugins/drone-webhook skip_verify: true method: POST auth: username: $$MANTL_USERNAME password: $$MANTL_PASSWORD urls: - https://$$MANTL_CONTROL/marathon/v2/apps/class/$$DOCKER_USERNAME/restart?force=true
#
